### ISSUE TITLE
Touch Event not handle correct on android

### ISSUE THREAD

**Issue by liaomin** [FaridSafi/react-native-gifted-messenger#1]
i'm not sure this proplem caused by InvertibleScrollView or this component,touch inverted on android.

**Comment by FaridSafi** [comment]
yes it's related to the invert, RN issue https://github.com/facebook/react-native/issues/3557
I recommend to use inverted={false} in Android until it's fixed in RN core

**Comment by FaridSafi** [comment]
It will be fixed in RN 0.17
https://github.com/exponentjs/react-native-invertible-scroll-view/issues/16
