### ISSUE TITLE
position left/right should not be stored in message json

### ISSUE THREAD

**Issue by josefrichter** [FaridSafi/react-native-gifted-messenger#10]
Found out you store position 'left' or 'right' directly in the message and then all the rendering conditions are based on that. However it probably shouldn't be stored in the message, because the very same message is 'right' on sender side, but 'left' on recipient side...

I'd suggest all messages store author ID instead and then you check each message's author ID against current user ID to determine if it's left or right.

Trying to figure out some quick monkey patch now - any tips?

**Comment by sibeliusseraphini** [comment]
@josefrichter I using your approach in my component - [Message.js](https://github.com/sibeliusseraphini/react-native-es6-messenger/blob/master/app/components/messages/Message.js) check it out, it was based on this component

**Comment by FaridSafi** [comment]
I think you can create an adapter for your needs, something like

```js
messages = messages.map(function(message) {
  return {
    // ...
    position: (message.authorID === currentUser.id ? 'right' : 'left')
    // ...
  }
});
```

**Comment by joaodematejr** [comment]
I am trying to do this test to start a message on the right side but it is not working could you help me please 

componentDidMount() {
        this.setState({
            messages: [
                {
                    _id: 1,
                    position: 'right',
                    text: 'Hello developer',
                    createdAt: new Date(),
                    user: {
                        _id: 1,
                        name: 'React Native',
                        avatar: 'https://placeimg.com/140/140/any',
                    },
                },
            ]
        })
    }
