### ISSUE TITLE
0.5 borderTopWidth on textInputContainer renders with gray artifacts on iPhone 6s Plus

### ISSUE THREAD

**Issue by stinju** [FaridSafi/react-native-gifted-messenger#11]
FYI, the 0.5 value for borderTopWidth on textInputContainer produces gray artifacts for me on the iPhone 6s Plus:

![image](https://cloud.githubusercontent.com/assets/75614/11770180/ef03afdc-a1ac-11e5-8b8c-efe11361de53.png)

Setting the value to 1 instead of 0.5 fixes it.  I believe it's an issue with TextInput or something underneath this plugin.

Versions:
    "react-native": "0.16.0",
    "react-native-gifted-messenger": "0.0.6",

**Comment by FaridSafi** [comment]
Fixed in version 0.0.9

**Comment by stinju** [comment]
Thanks!
