### ISSUE TITLE
Reverse messages order and 'scroll to bottom'

### ISSUE THREAD

**Issue by aksonov** [FaridSafi/react-native-gifted-messenger#112]
As I understand messages should be sorted by time asc? If so why the component doesn't scroll to bottom to show 'latest' message?

**Comment by FaridSafi** [comment]
the messages are sorted by the order in the messages array

**Comment by aksonov** [comment]
Yes, i've seen this (however why they cannot be sorted by time?). The problem that the component doesn't scroll to bottom after load to show last (bottom) message.

**Comment by FaridSafi** [comment]
Yes you right, please see my last commit. I will implement this fix in the next release

**Comment by aksonov** [comment]
Thanks!
