### ISSUE TITLE
onKeyboardWillHide and onKeyboardWillShow not properly respecting maxHeight

### ISSUE THREAD

**Issue by niftylettuce** [FaridSafi/react-native-gifted-messenger#12]
The only visible part shown should be the height of the textInput (which isn't possible to pass textInputHeight right now).  Basically if I have buttons below my messenger, like a hamburger icon to go to a settings menu - then it won't respect the height of the hamburger icon container.  Therefore when keyboard is shown, stuff like this happens:

![screen shot 2015-12-14 at 1 36 42 am](https://cloud.githubusercontent.com/assets/523141/11774439/258ba400-a203-11e5-992c-086f444bff93.png)

**Comment by sibeliusseraphini** [comment]
I think it is a better approach to have another component for textInput instead (<MessageComposer />)

**Comment by FaridSafi** [comment]
if you still have this issue, can you submit a PR please

**Comment by jaywalklabs** [comment]
been struggling with this as well, the best solution i found was to hide the bottom tabbar menu when loading the messenger. Which looking at other apps seems to be best practice (FB messenger, Instagram, Skype, Whatsapp etc)
