### ISSUE TITLE
How to set leftControlBar

### ISSUE THREAD

**Issue by yosiyuki** [FaridSafi/react-native-gifted-messenger#132]
I'm new in react-native and gifted messenger is really helpful for me.

I want to add camera button with leftControlBar but don't understand how to set props.leftControlBar.
Please anyone help me.

**Comment by wenkesj** [comment]
@yosiyuki 

```
<GiftedMessenger
...
leftControlBar={<SomeComponent/>}
...
/>
```

I would suggest reading the React Native docs

**Comment by yosiyuki** [comment]
@wenkesj Thank you for your reply.

I did it but keep getting following error.

 `Element type is invalid expected a string (for built-in components) or a class/function`

**Comment by yosiyuki** [comment]
I resolved by myself.
Definition of <SomeComponent/> having a problem.

**Comment by wenkesj** [comment]
@yosiyuki np
