### ISSUE TITLE
wrap the content

### ISSUE THREAD

**Issue by narychen** [FaridSafi/react-native-gifted-messenger#15]
It seems wrapping the content within the bubble is a common stuff in every chatting apps.
But the flex row layout with flex=1 cannot wrap the content. You should specify a margin to permanently draw the size.
You could do with flex column layout just like the demo on https://rnplay.org/plays/6h_SzA?autoplay=true. But if layout in column the errorbutton and status text always lay in column with the bubble.
So how could it be fixed?

**Comment by narychen** [comment]
Plus the maxWidth seems not working with current react-native version.

**Comment by FaridSafi** [comment]
Hello @narychen,
There is a margin because I didn't succeed to implement dynamic content wrapping when I tried.
Feel free to submit a PR if you find a way to do it

**Comment by FaridSafi** [comment]
fixed by 0.0.11
