### ISSUE TITLE
Messages not updating with setState()

### ISSUE THREAD

**Issue by schmoove** [FaridSafi/react-native-gifted-messenger#157]
I can load initial messages fine, but when receiving and sending new ones, I can't for the life of me get the UI to update from the changed "messages" state, despite the state clearly changing:

![image](https://cloud.githubusercontent.com/assets/1321541/16710112/ec752608-45d8-11e6-8ba3-c0b98027db62.png)

Am I missing something obvious? 

To test, I set the "typingMessage" prop as follows:

![image](https://cloud.githubusercontent.com/assets/1321541/16710200/78af9b6a-45db-11e6-8181-f9cff655d6c0.png)

And it does in fact increment when messages are sent/received. But no messages appear :(

**Comment by schmoove** [comment]
Ok, my bad - this is actually a RN issue. You can't just update the "messages" object, you need to clone it, and update the state with that:

https://github.com/facebook/react-native/issues/4104

**Comment by wayne1203** [comment]
Hi @schmoove , how can you solve the problem?
I can't found where is the "dataSource" so not able to use cloneWithRow function.
