### ISSUE TITLE
Sender and receive images

### ISSUE THREAD

**Issue by skeie** [FaridSafi/react-native-gifted-messenger#17]
Hi,

I was wondering if its possible to display both the sender and receive images?  

So if you take this image as an example both grey and the blue bubble will have image 
![image](https://cloud.githubusercontent.com/assets/1346122/12151228/656d99ee-b4ae-11e5-9ae6-5fd255776daf.png)

**Comment by FaridSafi** [comment]
Yes its possible using the image attribute of message object

**Comment by skeie** [comment]
Hi again,

Thank you for quick response.  I have tried that, but it only shows the last message's icon. Not the first one in grey.

![image](https://cloud.githubusercontent.com/assets/1346122/12151551/05beefbe-b4b0-11e5-94ae-fd7b96104d4e.png)

As you can see here, the first object with the text "Hi, what can we do for you" has a images attribute:
![image](https://cloud.githubusercontent.com/assets/1346122/12151671/a1875d50-b4b0-11e5-9c15-3e3140150a7c.png)

but the images doesn't show. Do you know why?

**Comment by FaridSafi** [comment]
Its normal but you can implement an option to display not only the last message image

**Comment by skeie** [comment]
Ah, okey. By passing in a ```senderImage``` object?

**Comment by FaridSafi** [comment]
Sorry I misunderstood your question about the first grey message "hi...". Its not normal :)

**Comment by skeie** [comment]
Ah, sorry. It's was hard for me to explain the problem. Is it possible to fix?

**Comment by FaridSafi** [comment]
Yes I will check tonight or tomorrow

**Comment by skeie** [comment]
Thanks @FaridSafi!

**Comment by FaridSafi** [comment]
Hello, I couldn't reproduce your issue.
Can you try with a remote image ? image: {uri: 'https://facebook.github.io/react/img/logo_og.png'}

**Comment by skeie** [comment]
Yeah, i tried. Still same issue. It will only show the last message's image. What else can i try? Or what else info do you need?

**Comment by FaridSafi** [comment]
I published a new version with a new prop forceRenderImage, can you check if it solves your issue please?

**Comment by skeie** [comment]
Yeah, that did the trick, thank you!
