### ISSUE TITLE
focus

### ISSUE THREAD

**Issue by siwymilek** [FaridSafi/react-native-gifted-messenger#18]
After sending a message, focus is lost
![Screen](http://new.shover.us/f/1AhixE)

**Comment by FaridSafi** [comment]
Hello @siwymilek, which react-native version ?

**Comment by FaridSafi** [comment]
if you are talking about the keyboard return button, you need to use submitOnReturn={true}

**Comment by siwymilek** [comment]
I'm sorry i didn't explain my problem well enough. After sending message focus is lost and text input disappears, so I can't write next message. Look at my screen and note that there is no text input :/ Any clue?

**Comment by FaridSafi** [comment]
Normally it should work because of keyboardShouldPersistTaps={true} of the listView

Can you try to add at the end of the onSend method please:
this.refs.textInput.focus();

**Comment by siwymilek** [comment]
This solving my problem partially. Still can't hide and open again keyboard.

**Comment by FaridSafi** [comment]
which RN version are you using ?

**Comment by siwymilek** [comment]
0.1.7

**Comment by FaridSafi** [comment]
Are you embedding the component inside a ScrollView ? If yes you can try to embed it inside a View instead

**Comment by siwymilek** [comment]
Nope, I embedded component inside TabBarIOS.Item and then inside View.

**Comment by siwymilek** [comment]
Ok I got it. Navigation Bar moves down Messenger and then a part of component was hidden.

**Comment by FaridSafi** [comment]
Great, I close this issue then. Thank you
