### ISSUE TITLE
Slack-like interface

### ISSUE THREAD

**Issue by JonathanWi** [FaridSafi/react-native-gifted-messenger#19]
Hey!

Really like your component, and it was a nice addition to what I was building. My current app works with a slack-like interface for messaging. Is this something I can achieve easily with this component or is it really opinionated toward a iMessage/Messenger like app?

TL;DR: Would it be more work to code my own interface instead of using this one in order to reproduce the slack UX.

Thanks for your amazing work, 

Cheers

**Comment by FaridSafi** [comment]
Hello @JonathanWi, thank you for your feedbacks!
I think this component includes the minimal stuffs of a messaging app. It doesn't include images sending but all the styles are overwritable.
If I was you I guess I would fork it and modify the source directly

**Comment by JonathanWi** [comment]
Thank you @FaridSafi! 

I think it's the best solution, I will report back if I successfully implement a slack-like interface so that you can link to it in case some people run into the same need as me!

Cheers
