### ISSUE TITLE
Split this component in more components

### ISSUE THREAD

**Issue by sibeliusseraphini** [FaridSafi/react-native-gifted-messenger#2]
In renderRow is better to have another component to render it, like <Message>

So, in next implementations we could have different types of Messages, like a message that has a photo, or a Gif or Location.

Or a <Message> component could have a List of <MessageParts>, in this design we could have in the same Message more than one type of message, like text + gif + photo

**Comment by olivierlesnicki** [comment]
+1

**Comment by FaridSafi** [comment]
What do you think about adding a view param to the messages :
message = {
  view: <View><Image /></View>
  // ...
}
If a view is specified, it will be added inside the bubble.
The view can contains all kinds of custom components - image/location/gif/video/etc.

An "Import media" button will also be needed close to the TextInput to trigger an PopUp/ActionSheet

**Comment by olivierlesnicki** [comment]
I don't think it's a wise idea to put the `view` element inside the `message` object. Instead we should expose a: `renderMessage(message) {}`

**Comment by FaridSafi** [comment]
what about getInitialMessages ?

**Comment by sibeliusseraphini** [comment]
we should have a **type** inside each message, and the type will map it to the right component to render it

for instance
type: 'text' -> <MessageText />
type: 'image' -> <MessageImage />
type: 'gif' -> <MessageGif />
type: 'location' -> <MessageLocation />

one problem is how to make easy to add more message types

**Comment by FaridSafi** [comment]
I'm thinking about a solution similar to Media Attachment of https://github.com/jessesquires/JSQMessagesViewController

The media component will have to be added to the message object
Some default media components will be provided
The media can be a custom component following some rules

**Comment by sibeliusseraphini** [comment]
it could work, I will try to code something in the next two weeks

**Comment by FaridSafi** [comment]
fixed by 0.0.11

**Comment by FaridSafi** [comment]
Fixed by 0.0.18.
Thanks @tommoor 

Example:
```js
message = {
  view: <View><Image /></View>
  // ...
}
```
