### ISSUE TITLE
invalid space with NavigatorIOS

### ISSUE THREAD

**Issue by tantou** [FaridSafi/react-native-gifted-messenger#20]
I use `react-native-invertible-scroll-view` with NavigatorIOS
```js
class GiftedMessengerExample extends Component {
  render(){
return (
<ListView
            ref='listView'
            dataSource={this.state.dataSource}
            renderRow={this.renderRow}
            renderFooter={this.renderLoadEarlierMessages}
            style={this.styles.listView}
    
            renderScrollComponent={props => <InvertibleScrollView {...props} inverted />}
/>
);
}
}
class Nav extends Component{
  render(){
    return (
      <NavigatorIOS
        style={{flex:1}}
        initialRoute={{
          title: 'flex:1',
          component: GiftedMessengerExample
        }} />
      
      );
  }
}
```
and it has a invalid space at the bottom of listView
![image](https://cloud.githubusercontent.com/assets/1531645/12345093/83527bfa-bb7f-11e5-8c8c-86a78836f9fa.png)

### what's the reason?

**Comment by FaridSafi** [comment]
Hello @tantou, I saw https://github.com/exponentjs/react-native-invertible-scroll-view/issues/19 
Did you add automaticallyAdjustContentInsets={false} to gifted-messenger component or to other view ?
