### ISSUE TITLE
is it possible to add renderRow property so that I could write my own render function

### ISSUE THREAD

**Issue by pgmemk** [FaridSafi/react-native-gifted-messenger#26]
The component looks very cool and I would love to try it

Right now I am using 'react-native-invertible-scroll-view'. It allows me to render the message the way I need to. And since my chat contains not only simple messages but also structured messages this feature is a must to have for our application.

**Comment by FaridSafi** [comment]
Hello @pgmemk, you can use the prop renderCustomText
Example https://github.com/FaridSafi/react-native-gifted-messenger/pull/16

**Comment by FaridSafi** [comment]
Please re-open if it doesn't work. Also I recommend you to try with 0.0.11
