### ISSUE TITLE
After loading earlier messages listview should stay at same scroll position

### ISSUE THREAD

**Issue by FaridSafi** [FaridSafi/react-native-gifted-messenger#28]

**Comment by terrysahaidak** [comment]
Hi @FaridSafi, I'm running into the same issue with my app. Did you find any solution?

**Comment by aymericbouzy** [comment]
I've never done it myself, but the way I would try to do it is:
* store the scroll position using the onScroll prop of the ScrollView component
* when loading new messages, use the scrollTo method of your ScrollView component to keep the same scroll position.

**Comment by FaridSafi** [comment]
fixed in 0.1.0

**Comment by Helongzhou** [comment]
Did it fixed?

**Comment by ArietNyshanbaev** [comment]
In my case I am facing current issue only when I do set inverted={false} otherwise everything is fine.
