### ISSUE TITLE
0.0.11 doesn't work

### ISSUE THREAD

**Issue by regeda** [FaridSafi/react-native-gifted-messenger#29]
I have been updated to the new version and got that:

![simulator screen shot 18 jan 2016 17 25 08](https://cloud.githubusercontent.com/assets/199553/12393711/7fb7ccda-be08-11e5-920c-82da3aae6a70.png)

**Comment by FaridSafi** [comment]
Hello, which RN version ?

**Comment by regeda** [comment]
@FaridSafi 0.17

**Comment by FaridSafi** [comment]
Thank you for reporting this issue, I published a new version

**Comment by FaridSafi** [comment]
I recommend to use this version with React-Native >= v0.18.0-rc (onLayout prop on ListView is required)

**Comment by niftylettuce** [comment]
Ah, so we need RN >= v0.18.0-rc...  Per #35 that might be its issue perhaps (I'm using RN 0.16)?  Can you please make aware somehow in the Readme or something?
