### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by kinhunt** [FaridSafi/react-native-gifted-messenger#3]
Hi:

No doubt this is a very cool component. 

I tried and hit the performance issue of ListView. When the number of messages increases, the response of 'send' button will be getting noticeably slower. 

Any solutions for this?

**Comment by FaridSafi** [comment]
Can you test the same performance test using inverted={false} please ?

**Comment by kinhunt** [comment]
@FaridSafi thank you. it's much better with inverted={false}. But the user experience is weird. I tried an App called Squad. It is in RN's show case, it's inverted messaging experience is smooth. I would recommend you to have a look.

**Comment by FaridSafi** [comment]
I'm trying to reach Squad team to ask how they did. Do you know one of their developers ?

In the meantime, if it's urgent for you to find a temporary fix, you can try to remove the borderRadius of bubbles/avatars and maybe to set removeClippedSubviews={true} (should already be true)

**Comment by kinhunt** [comment]
@FaridSafi , I tried to reach Dan Horrigan at the Squad team, but didn't get reply. Please try. Thanks for the tips.

**Comment by FaridSafi** [comment]
I had no answer from Dan Horrigan.
I guess we can improve the performance by not using react-native-invertible-scroll-view anymore.
For that, the scrolling of the listview has to be initialized at the end of the list.
If someone knows how to scroll to the end of a listview I'm interested.

**Comment by kinhunt** [comment]
@FaridSafi I agree with you. I suppose we can use the 'getMetrics' method to get the content height of ListView and use its scrollresponder to scroll to bottom.

Content height - Container heigh

**Comment by FaridSafi** [comment]
I will try today

**Comment by josefrichter** [comment]
not sure if this is the same problem, but I noticed serious performance issues because of onChangeText method being fired on each key press. so basically if you typed a long message quite fast, the Send button is unresponsive for considerable time. could that be the root of this problem?

**Comment by FaridSafi** [comment]
I got some issues with RN 0.17.0-RC and babel things.
So I will wait for final 0.17.0 release then I will look for all issues.

**Comment by kinhunt** [comment]
I tired to invert the messages without using react-native-invertible-scroll-view. 

How I do:
1. After rendering initial messages. scroll to bottom
2. After loading earlier messages. scroll to pervious position.

It works, and the performance is good. Only problem is that users can see the list is automatically scrolling. Any idea how to improve this?

**Comment by FaridSafi** [comment]
did you try scrollWithoutAnimationTo() instead of scrollTo() ?

**Comment by FaridSafi** [comment]
@kinhunt Regarding the scroll to bottom, I found this
http://stackoverflow.com/questions/29829375/how-to-scroll-to-bottom-in-react-native-listview/34838513#34838513

**Comment by FaridSafi** [comment]
@kinhunt I'm working also on stop using react-native-invertible-scroll-view
How did you manage to "2. After loading earlier messages. scroll to pervious position." ?

**Comment by FaridSafi** [comment]
fixed by 0.0.11

invertible-scroll-view removed

**Comment by matviyiv** [comment]
So how can I get version 0.0.11 it wasn't published to npm?
