### ISSUE TITLE
React-native-inveritble-scroll-view

### ISSUE THREAD

**Issue by skeie** [FaridSafi/react-native-gifted-messenger#32]
Hi, I am trying to use gifted messenger.

I get this follow error on 0.0.10:

![image](https://cloud.githubusercontent.com/assets/1346122/12454441/d28e13fc-bf97-11e5-96c3-c8ef7003ab76.png)

Any tips to solve this?

**Comment by FaridSafi** [comment]
Hello, please try with 0.0.14

**Comment by skeie** [comment]
Thanks, sorry for not trying that.
