### ISSUE TITLE
There is no "load earlier messages" button 

### ISSUE THREAD

**Issue by siwymilek** [FaridSafi/react-native-gifted-messenger#33]
There is no "load earlier messages" button in my component. Any clue?
![Screenshot](http://i.imgur.com/joG4vcH.jpg)

Code:
```
<GiftedMessenger
    ref={(c) => this._GiftedMessenger = c}
    ...
    loadEarlierMessagesButton={true}
    loadEarlierMessagesButtonText="Load"
    ...
/>
```

**Comment by FaridSafi** [comment]
Hello, maybe it's because of https://github.com/FaridSafi/react-native-gifted-messenger/blob/master/GiftedMessenger.js#L224

Did you set initial "messages" prop with data ?

**Comment by kesha-antonov** [comment]
Hey guys.
This is my render method:

```
  ...
  ref: (c) ->
    @_GiftedMessenger = c

  render: ->
    <GiftedMessenger
      style={styles.chatContainer}
      ref={@ref}

      messages={[]}
      handleSend={@handleSend}
  ...
```
This solved it for me:
```
  ...
  componentDidMount: ->
    @_GiftedMessenger.setState(allLoaded: false)
    @loadMsgs()
  ...
```

**Comment by FaridSafi** [comment]
please re-open if you are still experimenting this issue with 0.1.0
