### ISSUE TITLE
Android: No messages show up on load when populating from remote service

### ISSUE THREAD

**Issue by corymsmith** [FaridSafi/react-native-gifted-messenger#35]
Works fine on iOS, any ideas?

**Comment by FaridSafi** [comment]
Hello, I published version 0.0.15.
Can you retry please?

https://github.com/FaridSafi/react-native-gifted-messenger/commit/f002bf7a4585ece207d8120f8a0a10fe9c3b5ece

**Comment by corymsmith** [comment]
Tried with 0.0.15 and still have the same issue.

**Comment by FaridSafi** [comment]
Did you try to scroll down the listview to see the messages (maybe the auto scroll didn't trigger) ?
Sorry but I can not reproduce this issue. If you find a solution can you submit a PR please

**Comment by corymsmith** [comment]
In componentDidMount I'm fetching messages and iterating through them to format them. I've tried both appendMessage and appendMessages with the whole array and on Android nothing appears, even when there's 20 messages to show. Doesn't seem like there's anything to scroll. I'm offline all day so can have a look tomorrow or this weekend.

**Comment by niftylettuce** [comment]
I have the same issue, using PubNub.

**Comment by niftylettuce** [comment]
I'm on 0.0.16 btw

**Comment by niftylettuce** [comment]
It almost renders for a split second and then it seems to disappear fwiw.

**Comment by niftylettuce** [comment]
Okay I added some console.log's into the codebase and pulled it up on Android to test.

It looks like the message gets appended, but then it gets removed.

**Comment by niftylettuce** [comment]
Caught this error while running Android Studio `KeyEvent: ACTION_UP but key was not down.` not sure if that is related.

**Comment by niftylettuce** [comment]
Also this `02-03 22:27:16.811 1500-3749/com.android.inputmethod.latin E/Surface: getSlotFromBufferLocked: unknown buffer: 0xab7982c0`

**Comment by niftylettuce** [comment]
Perhaps the reason why mine isn't working is because I'm on RN v0.17 and this seems to require RN >= v0.18.0-rc per #29 (due to onLayout being required per https://github.com/facebook/react-native/releases/tag/v0.18.0).

**Comment by FaridSafi** [comment]
@corymsmith do you still have the issue with RN >= 0.18.0?

**Comment by FaridSafi** [comment]
@niftylettuce Thank you for your investigations. Yes it requires onLayout prop, I already added in the readme

**Comment by niftylettuce** [comment]
Awesome, yeah that should be the reason why it doesn't work for @corymsmith too.
