### ISSUE TITLE
renderRow gets called when only renderHeader should

### ISSUE THREAD

**Issue by lablz** [FaridSafi/react-native-gifted-messenger#38]
this setState causes it: https://github.com/FaridSafi/react-native-gifted-messenger/blob/master/GiftedMessenger.js#L298

btw, thanks for making this!

**Comment by FaridSafi** [comment]
Hello, the component forces re-rendering of rows which have/had a status
I can't try now but I suggest you to replace line 396
https://github.com/FaridSafi/react-native-gifted-messenger/blob/master/GiftedMessenger.js#L396
by 
```js
delete this._data[i].status;
```

**Comment by FaridSafi** [comment]
please re-open if you are still experimenting this issue with 0.1.0
