### ISSUE TITLE
drag (pull) down at the top of the page for loading earlier messages

### ISSUE THREAD

**Issue by pgmemk** [FaridSafi/react-native-gifted-messenger#39]
Thank you for your awesome component!

Is it possible to add functionality to have a choice between button and pull down for loading the earlier messages?

**Comment by FaridSafi** [comment]
Hello @pgmemk,
Sorry but I don't plan to implement this feature.
You still can do and I will be glad to merge a PR.

I recommend to try with https://facebook.github.io/react-native/docs/refreshcontrol.html#content

**Comment by giantss** [comment]
@FaridSafi Alas, this is actually a basic function that can greatly improve the user experience.
