### ISSUE TITLE
Android Keyboard events not working?

### ISSUE THREAD

**Issue by niftylettuce** [FaridSafi/react-native-gifted-messenger#43]
Hey, had this issue last night I think... Here was my note:

> Why is this still commented as is?  Is it not working on RN v0.18+?  It doesn't seem to work for me.  https://github.com/FaridSafi/react-native-gifted-messenger/blob/master/GiftedMessenger.js#L441-L444

**Comment by niftylettuce** [comment]
Oh, it's the `onKeyboardWillHide` and `onKeyboardWillShow`, those two events don't trigger on Android RN v0.18+.  This is because it's now built in (see documentation update note here) https://github.com/johanneslumpe/react-native-keyboardevents#react-native-keyboardevents.  Maybe we should be using this instead?

**Comment by niftylettuce** [comment]
https://github.com/facebook/react-native/issues/3468

**Comment by FaridSafi** [comment]
We can use DidShow and DidHide in Android

**Comment by niftylettuce** [comment]
@FaridSafi I basically took out all of the keyboard events in my package, and then used the the ref as `this._GiftedMessenger` to handle events.  However I still have a weird state issue, where messages get hidden if I change view, like they don't get set in state.

**Comment by FaridSafi** [comment]
fixed by using `onKeyboardDidShow` and `onKeyboardDidHide` instead of `onKeyboardWillShow` and `onKeyboardWillHide` in Android
