### ISSUE TITLE
Should we make keyboardShouldPersistTaps={false} by default?

### ISSUE THREAD

**Issue by niftylettuce** [FaridSafi/react-native-gifted-messenger#47]
It seems to me that a user would want to be able to dismiss the keybaord whenever they click back on the messages window (like how normal iOS and Android messaging apps work).  Do you agree we should make this the new default?  Right now it is set to true.

**Comment by DeeBrad** [comment]
I agree

**Comment by koppelaar** [comment]
The property is now exposed. We haven't changed the default, but at least you can set it yourself, so I suggest closing this issue.

**Comment by FaridSafi** [comment]
I don't recommend to use keyboardShouldPersistTaps={false}  because you will need to tap twice to 'Load earlier messages'
