### ISSUE TITLE
how to add icon upload etc near/inside message input placeholder?

### ISSUE THREAD

**Issue by radiegtya** [FaridSafi/react-native-gifted-messenger#52]
how to add icon upload etc near/inside message input placeholder?
so when I click it, i can upload or handle click something.

**Comment by FaridSafi** [comment]
Hello @radiegtya, this is not supported.
You can implement it by editing source https://github.com/FaridSafi/react-native-gifted-messenger/blob/master/GiftedMessenger.js#L478 and maybe submit a pull request

**Comment by radiegtya** [comment]
ok Thanks @FaridSafi

**Comment by xstable** [comment]
Would be a great feature, because I wan't to add "voice-recording" to the chat.
Please reopen the Ticket, so that people who interested in this can participate.
