### ISSUE TITLE
"this._data[rowID].position" becomes undefined when using ES6

### ISSUE THREAD

**Issue by ensorrow** [FaridSafi/react-native-gifted-messenger#54]
I copied your example and changed it into ES6 and it went wrong when I tried to do `this._GiftedMessenger.setMessageStatus('ErrorButton', rowID);`. It said `undefined is not an object(evaluating'this._data[rowID].position')`.

(I have already bind `this` using =>)

**Comment by FaridSafi** [comment]
API changed in 0.1.0. Please see https://github.com/FaridSafi/react-native-gifted-messenger/blob/master/GiftedMessengerExample/GiftedMessengerContainer.js#L134
