### ISSUE TITLE
Broken first time scroll to bottom feature

### ISSUE THREAD

**Issue by Kudo** [FaridSafi/react-native-gifted-messenger#55]
Not sure if anyone faced my issue.
My GiftedMessenger does not auto scroll to bottom from first time display.
After digging the code, I found the reason is from the onLayout sequence.
My onLayout sequences is footerView(with footerY=0) -> ListView -> footerView(with correct footerY).
(I use redux and guess the onLayout sequence behaviours comes from re-render flow.)
Then first time scrollWithoutAnimationToBottom() will do nothing since the footerY is 0.

Here is an easy fix but not elegant and would like to see if anyone has similar issues.
https://github.com/FaridSafi/react-native-gifted-messenger/compare/master...Kudo:fixFirstScrollToBottom

**Comment by FaridSafi** [comment]
Hello, are you using rn .20 ?
last version is compatible only with rn 0.20.0 due to scrollTo breaking changes

**Comment by Kudo** [comment]
Sorry forgot to provide this information.
Yes, I use RN 0.20.0.

**Comment by Kudo** [comment]
One more finding, I faced #33 issue as well.
It seems I should prevent to re-render GiftedMessenger, i.e.
```javascript
render() {
  let {messages} = this.props;
  if (messages.length === 0) {
    // Before data is loaded, render a stub view.
    return <View style={styles.container} />;
  }
  return (
    <GiftedMessenger
      messages={messages}
    />
  );
}
```

For such solution, both this scrollToBottom and #33 are solved for me.

**Comment by Kudo** [comment]
Let me close this since there is a solution. Thanks
