### ISSUE TITLE
JSON value ... of type NSDictionary cannot be converted to NSNumber

### ISSUE THREAD

**Issue by yogiben** [FaridSafi/react-native-gifted-messenger#58]
Error occurs once there are a few (8+) messages on the screen. I'm pretty sure it's not from my code.

Any ideas would be much appreciated.

https://github.com/facebook/react-native/issues/3340
https://github.com/facebook/react-native/issues/3300

![image](https://cloud.githubusercontent.com/assets/1703155/13256885/c29d1f4a-da4c-11e5-9bb4-b4622669f330.png)

**Comment by FaridSafi** [comment]
Hello, are you using react-native 0.20.0 ?

**Comment by yogiben** [comment]
That fixed it.

**Comment by chenqitao** [comment]
How did you fix it?I have the same mistake!

**Comment by zilan830** [comment]
I also want to konw.Please tell me how to fix it.Thank you.
