### ISSUE TITLE
bubble angle

### ISSUE THREAD

**Issue by narychen** [FaridSafi/react-native-gifted-messenger#6]
Cool and beautiful component. But the chatting bubble missing the angle which pointer to the avatar. I wonder how to fix this

**Comment by FaridSafi** [comment]
I think a good solution will be to use a PNG image and to apply a tintColor to have the same color as the background bubbles. The angle should be displayed only when the row displays the avatar.
If you manage to implement it, a PR will be very appreciated

**Comment by kenkotch** [comment]
I was able to solve this by adding a view behind the chat bubble like so:
```
const renderBubble = useCallback((props) => (
  <View>
    <Bubble {...props} />
    <View
      style={[styles.triangle, props.position === 'left' ? styles.leftTriangle : styles.rightTriangle]}
    />
  </View>
), []);

const styles = StyleSheet.create({
  triangle: {
    position: 'absolute',
    top: -7.5,
    width: 0,
    height: 0,
    backgroundColor: 'transparent',
    borderStyle: 'solid',
    borderTopWidth: 30,
    borderRightWidth: 10,
    borderBottomWidth: 30,
    borderLeftWidth: 10,
    borderTopColor: 'transparent',
    borderRightColor: 'transparent',
    borderLeftColor: 'transparent',
    zIndex: -10,
  },
  leftTriangle: {
    borderBottomColor: 'blue',
    left: -20,
    transform: [{ rotate: '-90deg' }],
  },
  rightTriangle: {
    borderBottomColor: 'blue',
    right: -20,
    transform: [{ rotate: '90deg' }],
  },
});
```

<img width="413" alt="Screen Shot 2020-05-30 at 3 44 03 PM" src="https://user-images.githubusercontent.com/4110008/83339559-70cfa900-a28c-11ea-9afc-53a374e98e4f.png">
