### ISSUE TITLE
[Android] TextInput not showing on top of keyboard

### ISSUE THREAD

**Issue by Mokto** [FaridSafi/react-native-gifted-messenger#60]
CF Screenshot

![screenshot_2016-02-23-18-07-42](https://cloud.githubusercontent.com/assets/5103928/13269897/7b59d0ea-da58-11e5-8e6c-c7108df13b63.png)

Thanks !

**Comment by FaridSafi** [comment]
Hello @Mokto, can you test if onKeyboardWillShow is triggered ? https://github.com/FaridSafi/react-native-gifted-messenger/blob/master/GiftedMessenger.js#L448

**Comment by Mokto** [comment]
Sure !!

I also have to say that I'm using 0.19.0.

**Comment by FaridSafi** [comment]
You should update to react-native 0.20.0 because scrollTo is not compatible backward

**Comment by Mokto** [comment]
The problem is that upgrading to 0.20 RN prevents me from using custom .babelrc files (I have not managed to make it work yet).

I just tried, onKeyboardWillShow is not triggered. ;)

**Comment by FaridSafi** [comment]
in your case, maybe you can move the content of onKeyboardWillShow to onKeyboardDidShow

**Comment by FaridSafi** [comment]
If you want to stay with 0.19.0 you need to revert changes of https://github.com/FaridSafi/react-native-gifted-messenger/commit/b0b56758ce9f8196aec7446ecad24c231fde61d6

**Comment by Mokto** [comment]
Ok, I just succeeded to install react-native 0.20 and updated your library to 0.20.0.

Still no textinput on top of keyboard ;)

**Comment by Mokto** [comment]
onKeyboardWillShow is still not triggered !

**Comment by Mokto** [comment]
Sorry for the spam ^^

But I did move 

```
Animated.timing(this.state.height, {
      toValue: this.listViewMaxHeight - (e.endCoordinates ? e.endCoordinates.height : e.end.height),
      duration: 200,
    }).start();
```

to onKeyboardDidShow and it works on Android.

It is really weird. What can we do to make this compatible for Android and ios ?
