### ISSUE TITLE
How to add some obj to handleSend?

### ISSUE THREAD

**Issue by radiegtya** [FaridSafi/react-native-gifted-messenger#61]
for example in handle send I want to add "channelId" field inside message before send it to server.

```
handleSend(message = {}, rowID = null) {
   /*state or props is not working here (i want dynamically get the channelId), because this are refer to message, not parent class itself*/
   message.channelId = this.state.channelId; 
   
  Meteor.call('Messages.insert', message);
};
```

Please Help

**Comment by FaridSafi** [comment]
Hello
Maybe you can try <GiftedMessenger handleSend={this.handleSend.bind(this)} />

**Comment by radiegtya** [comment]
Nice and easy!
Thanks, sorry I am still one day trying to code on React. This plugin is cool! 
I'll close this
