### ISSUE TITLE
Unable to run the project

### ISSUE THREAD

**Issue by satish-gathole-driveu** [FaridSafi/react-native-gifted-messenger#62]
I am new on React Native and learning by looking at the examples... I was trying to setup and run this project but unable to do so... As per readme file I ran the command `npm install react-native-gifted-messenger --save`  but after that I was running following command and getting error

```
Admins-MacBook-Pro:GiftedMessengerExample gathole$ react-native run-android
Command `run-android` unrecognized. Did you mean to run this inside a react-native project?
```
any help would be appreciated

**Comment by FaridSafi** [comment]
Hello, you can try to do ```npm install``` before ```react-native run-android```

**Comment by satish-gathole-driveu** [comment]
It worked Thanks Farid :)
