### ISSUE TITLE
How can I reference local GiftedMessenger from example?

### ISSUE THREAD

**Issue by kristianmandrup** [FaridSafi/react-native-gifted-messenger#67]
Trying to change from `require 'react-native-gifted-messenger` to
`var GiftedMessenger = require('../');` so that I can debug and play with `GiftedMessenger.js`

But I get an error: `Unable to resolve module ...` 

Any ideas?

**Comment by kristianmandrup** [comment]
I tried copying all the files such as `GiftedMessenger.js` inside the examples folder, but getting other errors...

**Comment by bpeters** [comment]
you need to `npm install react-native-gifted-messenger --save` into your react-native project. Then you can require as normal.

**Comment by kristianmandrup** [comment]
What I meant by local is my local clone of `react-native-gifted-messenger`. 
I guess I could just use `npm link` ;)
