### ISSUE TITLE
Additional Button on the left side

### ISSUE THREAD

**Issue by maluramichael** [FaridSafi/react-native-gifted-messenger#74]
Is it possible to add buttons to the left side of the input box? Like a Camera button for image uploads.

**Comment by bpeters** [comment]
I added a PR that allows you to create a much more flexible custom display based on message row data. https://github.com/FaridSafi/react-native-gifted-messenger/pull/71

Here is an example of adding buttons inline in the chat: https://gyazo.com/de634181d3b27ffae7d6d04fbb649f9b

**Comment by maluramichael** [comment]
I think my question is not that clear. I thought of a button on the left side of the input field. 
<img width="444" alt="screen shot 2016-03-08 at 07 45 30" src="https://cloud.githubusercontent.com/assets/1489383/13594089/c7b4bba4-e501-11e5-8d5c-a16bc66d2ebb.png">

Like this one for uploading images/videos.

**Comment by peng051410** [comment]
+1

**Comment by bpeters** [comment]
Aw gotcha, it's not currently implemented. However, I can make another PR for this functionality. Basically, you should be able to over-ride the current text input container with your own container. Which could include anything.

**Comment by FaridSafi** [comment]
Hello, there is now a `leftControlBar` prop in 0.1.0
