### ISSUE TITLE
TextInput and Message Content jumps to top

### ISSUE THREAD

**Issue by BigPun86** [FaridSafi/react-native-gifted-messenger#75]
Hey there! I am trying to use this module for my RN Android APP (RN v0.20). When i initially open the component, everything seems to be fine. As soon as i type in a message the content will be displayed on top of the view:

![screen shot 2016-03-08 at 14 12 27](https://cloud.githubusercontent.com/assets/7880624/13602685/6a6402d4-e538-11e5-9638-5fc106337e2c.png)

The next time i open up the keyboard my textinput jumps to the top as well:

![screen shot 2016-03-08 at 14 12 39](https://cloud.githubusercontent.com/assets/7880624/13602654/315532f6-e538-11e5-9ca0-3115ea4285d1.png)

I am using the example code. Anyone with similar issue?

**Comment by pcxiong** [comment]
I have the same problem

**Comment by 8enmann** [comment]
same here

**Comment by timzaak** [comment]
Wrap it with a view
```html
<View style={marginTop:theNaviHeight}>
    <Gifted.../>
</View>
```

**Comment by 8enmann** [comment]
when i do that with the input not focused, the whole thing slides that far down

**Comment by 8enmann** [comment]
I found this fixed it for me:
  //toValue: this.listViewMaxHeight - (e.endCoordinates ?
e.endCoordinates.height : e.end.height),
   toValue: e.endCoordinates.screenY,

**Comment by aymericbouzy** [comment]
Hi @8enmann, can you explain a bit more your fix? I'm having the same problem.

**Comment by 8enmann** [comment]
Didn't actually work :/

**Comment by FaridSafi** [comment]
fixed in 0.1.0. Please see https://github.com/FaridSafi/react-native-gifted-messenger/blob/master/README.md#android-installation

**Comment by 8enmann** [comment]
Woohoo! thanks!

**Comment by AngSin** [comment]
@8enmann did it work for you? I am facing this problem with version 0.4.3

**Comment by AngSin** [comment]
@8enmann , thanks for the quick reply, but it's fine it worked for me by changing `bottomOffset` to the total height of the window - height of the area below the GiftedChat (for e.g. a tab navigation or some other component) :)
