### ISSUE TITLE
Listview doesn't scroll down after posting a new message

### ISSUE THREAD

**Issue by koppelaar** [FaridSafi/react-native-gifted-messenger#78]
When the Listview is scrolled all the way down, and you send a new message (or receive one) the Listview should scroll down instantly to show the new mesaage, but this doesn't happen which makes new messages undiscoverable.

**Comment by DVassilev** [comment]
+1

**Comment by FaridSafi** [comment]
fixed in 0.0.24

**Comment by DVassilev** [comment]
@FaridSafi I don't think this is fixed. It only scrolls to halfway through the message for me.

**Comment by jonlaing** [comment]
I'm having a similar issue. One thing to note is that I'm adding padding to the listView to offset from a custom navbar. It seems like the messenger thinks it's taller than it is.

```jsx

class Chat extends Component {

  // ...

  // NavBar is position: absolute
  render() {
    return (
      <View style={{flex: 1 }} >
        <Messenger
          messages={this.state.messages}
          autoScroll={true}
          forceRenderImage={true}
          onCustomSend={this._handleSend.bind(this)}
          styles={{ listView: styles.listView, bubbleRight: styles.bubbleRight }}
          ref="chat"
        />
        <NavBar
          title={`@${this.props.user.username}`}
          leftButton={ <Icon name="chevron-left" color="rgb(255,255,255)" size={24} /> }
          leftButtonPress={() => this.props.navigator.pop()}
        />
      </View>
    );
  }
}

let styles = StyleSheet.create({
  listView: {
    flex: 1,
    paddingTop: Layout.lines(4) // This is the height of the navbar
  }
});

```

**Comment by jonlaing** [comment]
![screen shot 2016-04-11 at 3 21 45 am](https://cloud.githubusercontent.com/assets/869620/14419556/9c0932c0-ff94-11e5-8ef5-21c8559d5204.png)

**Comment by ianlin** [comment]
@jonlaing Can you please try adding `paddingTop` in `container` instead of `listView`?

For instance, here is the diff of your code snippet:

```diff
@@ -13,7 +13,7 @@
           autoScroll={true}
           forceRenderImage={true}
           onCustomSend={this._handleSend.bind(this)}
-          styles={{ listView: styles.listView, bubbleRight: styles.bubbleRight }}
+          styles={{ container: styles.container, bubbleRight: styles.bubbleRight }}
           ref="chat"
         />
         <NavBar
@@ -27,7 +27,7 @@
 }

 let styles = StyleSheet.create({
-  listView: {
+  container: {
     flex: 1,
     paddingTop: Layout.lines(4) // This is the height of the navbar
   },
```

**Comment by jonlaing** [comment]
![screen shot 2016-04-11 at 2 39 51 pm](https://cloud.githubusercontent.com/assets/869620/14438287/4ea0bcf6-fff3-11e5-83df-df483875ecb8.png)

The TextInput sits below the keyboard, and still clips the last message a bit.

**Comment by FaridSafi** [comment]
Hello guys, i'll publish a fix this week
