### ISSUE TITLE
Tapping a single time on the Listview should dismiss the keyboard

### ISSUE THREAD

**Issue by koppelaar** [FaridSafi/react-native-gifted-messenger#80]
The most common way for messenger apps to dismiss the keyboard is not through scroll interactions but by simply tapping the Listview (that contains the messages) once. GiftedMessenger does not do this, which makes it quite hard for users to dismiss the keyboard, I've noticed.

**Comment by kelvinaliyanto** [comment]
@koppelaar I am having trouble with this. Now simply tapping the MessageContainer does not dismiss the keyboard on Android.
