### ISSUE TITLE
Message ID instead of RowID

### ISSUE THREAD

**Issue by DVassilev** [FaridSafi/react-native-gifted-messenger#87]
Is it possible to set status by the ID attribute of the messages (that is sent from the server) as opposed to having to store RowID?

**Comment by FaridSafi** [comment]
Hello, this is currently not possible. An implementation pull request of a built-in feature would be appreciated

**Comment by FaridSafi** [comment]
Hello, this is implemented in 0.1.0. Please see https://github.com/FaridSafi/react-native-gifted-messenger/blob/master/GiftedMessengerExample/GiftedMessengerContainer.js#L134
